import type { Essay, Person, Scholarship } from "./types"

export const COUNTRIES = ["Rwanda", "Kenya", "Uganda", "Ghana", "Nigeria", "India", "Other"]
export const FIELDS = ["Computer Science", "Engineering", "Public Health", "Business", "Education", "Agriculture", "Law", "Other"]

const africa = ["Rwanda", "Kenya", "Uganda", "Ghana", "Nigeria"]

// ---------------------------------------------------------------------------
// Sample data. Details are illustrative: always confirm on the provider's site.
// In a real product this comes from your API (see lib/api.ts).
// ---------------------------------------------------------------------------
export const scholarships: Scholarship[] = [
  {
    id: "chevening",
    name: "Chevening Scholarship",
    provider: "UK Foreign, Commonwealth & Development Office",
    country: "United Kingdom",
    levels: ["Master's"],
    fields: ["Any"],
    nationalities: "any",
    minGpa: 3.0,
    amountLabel: "Full funding",
    amountValue: 60000,
    fullyFunded: true,
    coverage: ["Tuition", "Monthly stipend", "Return flights", "Visa costs"],
    deadline: "2026-11-03",
    postedAt: "2026-09-14",
    about: "One-year master's at a UK university for emerging leaders. Selection weighs leadership, networking and a clear plan for what you will do when you return home.",
    essayPrompt: "Describe a moment you led others to change something, and how a UK master's will help you do more of it.",
    essayTarget: 500,
    documents: ["Passport", "Academic transcripts", "CV", "Proof of 2 years' work experience"],
    referencesNeeded: 2,
    url: "https://www.chevening.org",
  },
  {
    id: "mastercard-foundation",
    name: "Mastercard Foundation Scholars",
    provider: "Mastercard Foundation partner universities",
    country: "Multiple",
    levels: ["Undergraduate", "Master's"],
    fields: ["Any"],
    nationalities: africa,
    minGpa: 3.2,
    amountLabel: "Full funding",
    amountValue: 50000,
    fullyFunded: true,
    coverage: ["Tuition", "Accommodation", "Living stipend", "Mentoring", "Laptop"],
    deadline: "2026-12-15",
    postedAt: "2026-09-24",
    about: "For academically talented young people from Africa who show financial need and a commitment to giving back to their communities.",
    essayPrompt: "Tell us about a challenge in your community and how your studies will help you address it.",
    essayTarget: 600,
    documents: ["National ID or passport", "Transcripts", "Proof of financial need", "Community service evidence"],
    referencesNeeded: 1,
    url: "https://mastercardfdn.org/all/scholars/",
  },
  {
    id: "daad",
    name: "DAAD Development-Related Postgraduate Courses",
    provider: "German Academic Exchange Service",
    country: "Germany",
    levels: ["Master's", "PhD"],
    fields: ["Computer Science", "Engineering", "Public Health", "Agriculture", "Business"],
    nationalities: "any",
    minGpa: 3.0,
    amountLabel: "€934 / month + costs",
    amountValue: 25000,
    fullyFunded: true,
    coverage: ["Monthly stipend", "Health insurance", "Travel allowance", "Study allowance"],
    deadline: "2026-10-31",
    postedAt: "2026-08-20",
    about: "Postgraduate study in Germany for professionals from developing countries with at least two years of work experience.",
    essayPrompt: "Explain how the chosen programme fits your career plan and your country's development needs.",
    essayTarget: 450,
    documents: ["CV (Europass)", "Motivation letter", "Transcripts", "Language certificate"],
    referencesNeeded: 2,
    url: "https://www.daad.de",
  },
  {
    id: "fulbright",
    name: "Fulbright Foreign Student Program",
    provider: "U.S. Department of State",
    country: "United States",
    levels: ["Master's", "PhD"],
    fields: ["Any"],
    nationalities: "any",
    minGpa: 3.3,
    amountLabel: "Full funding",
    amountValue: 55000,
    fullyFunded: true,
    coverage: ["Tuition", "Living stipend", "Health insurance", "Airfare"],
    deadline: "2027-02-10",
    postedAt: "2026-09-28",
    about: "Graduate study in the U.S. Applications go through your home-country Fulbright commission or embassy.",
    essayPrompt: "Present your study objectives and how you will share what you learn once you return.",
    essayTarget: 650,
    documents: ["Transcripts", "Study objectives", "English test score"],
    referencesNeeded: 3,
    url: "https://foreign.fulbrightonline.org",
  },
  {
    id: "gates-cambridge",
    name: "Gates Cambridge Scholarship",
    provider: "University of Cambridge",
    country: "United Kingdom",
    levels: ["Master's", "PhD"],
    fields: ["Any"],
    nationalities: "any",
    minGpa: 3.7,
    amountLabel: "Full cost of study",
    amountValue: 70000,
    fullyFunded: true,
    coverage: ["Tuition", "Maintenance", "Airfare", "Discretionary funding"],
    deadline: "2026-12-03",
    postedAt: "2026-08-30",
    about: "Highly competitive. Looks for outstanding intellectual ability, leadership potential and a commitment to improving others' lives.",
    essayPrompt: "How will your work improve the lives of others?",
    essayTarget: 500,
    documents: ["Transcripts", "Research proposal", "CV"],
    referencesNeeded: 3,
    url: "https://www.gatescambridge.org",
  },
  {
    id: "erasmus-mundus",
    name: "Erasmus Mundus Joint Master's",
    provider: "European Union",
    country: "Europe",
    levels: ["Master's"],
    fields: ["Any"],
    nationalities: "any",
    minGpa: 3.0,
    amountLabel: "Up to €1,400 / month",
    amountValue: 35000,
    fullyFunded: true,
    coverage: ["Tuition", "Travel", "Installation costs", "Monthly allowance"],
    deadline: "2027-01-15",
    postedAt: "2026-09-26",
    about: "Study in two or more European countries. You apply to each programme directly, and deadlines vary.",
    essayPrompt: "Why this programme, and what do you want to be doing five years after graduating?",
    essayTarget: 400,
    documents: ["CV", "Transcripts", "Language certificate"],
    referencesNeeded: 2,
    url: "https://erasmus-plus.ec.europa.eu",
  },
  {
    id: "commonwealth",
    name: "Commonwealth Master's Scholarship",
    provider: "Commonwealth Scholarship Commission",
    country: "United Kingdom",
    levels: ["Master's", "PhD"],
    fields: ["Any"],
    nationalities: [...africa, "India"],
    minGpa: 3.0,
    amountLabel: "Full funding",
    amountValue: 45000,
    fullyFunded: true,
    coverage: ["Tuition", "Stipend", "Airfare", "Thesis grant"],
    deadline: "2026-10-22",
    postedAt: "2026-09-01",
    about: "For students from lower and middle income Commonwealth countries who cannot afford to study in the UK.",
    essayPrompt: "Describe how your study will contribute to development in your home country.",
    essayTarget: 500,
    documents: ["Transcripts", "Proof of financial need", "Development impact statement"],
    referencesNeeded: 2,
    url: "https://cscuk.fcdo.gov.uk",
  },
  {
    id: "mext",
    name: "MEXT Undergraduate Scholarship",
    provider: "Government of Japan",
    country: "Japan",
    levels: ["Undergraduate"],
    fields: ["Engineering", "Computer Science", "Business", "Education", "Agriculture"],
    nationalities: "any",
    minGpa: 3.0,
    amountLabel: "¥117,000 / month + costs",
    amountValue: 20000,
    fullyFunded: true,
    coverage: ["Tuition waiver", "Monthly stipend", "Airfare", "Japanese language year"],
    deadline: "2027-03-05",
    postedAt: "2026-09-10",
    about: "Five-year programme including a preparatory Japanese language year. Applicants must be under 25.",
    essayPrompt: "Why do you want to study in Japan, and what will you study?",
    essayTarget: 400,
    documents: ["Passport", "Transcripts", "Health certificate", "Application forms"],
    referencesNeeded: 1,
    url: "https://www.studyinjapan.go.jp",
  },
]

/** Scholarships that "get posted later". lib/api.ts hands these out when the student checks for new ones. */
export const incomingPool: Omit<Scholarship, "postedAt">[] = [
  {
    id: "swiss-excellence",
    name: "Swiss Government Excellence Scholarships",
    provider: "Swiss Confederation",
    country: "Switzerland",
    levels: ["Master's", "PhD"],
    fields: ["Any"],
    nationalities: "any",
    minGpa: 3.3,
    amountLabel: "CHF 1,920 / month",
    amountValue: 30000,
    fullyFunded: true,
    coverage: ["Monthly stipend", "Tuition exemption", "Health insurance", "Housing allowance"],
    deadline: "2026-12-10",
    about: "Research or postgraduate study at a Swiss university. Applications go through the Swiss embassy or a nominating authority in your country.",
    essayPrompt: "Describe your research or study plan and why Switzerland is the right place for it.",
    essayTarget: 500,
    documents: ["Research proposal", "Transcripts", "CV", "Language certificate"],
    referencesNeeded: 2,
    url: "https://www.sbfi.admin.ch",
  },
  {
    id: "rotary-peace",
    name: "Rotary Peace Fellowship",
    provider: "Rotary Foundation",
    country: "Multiple",
    levels: ["Master's"],
    fields: ["Any"],
    nationalities: "any",
    minGpa: 3.0,
    amountLabel: "Full funding",
    amountValue: 55000,
    fullyFunded: true,
    coverage: ["Tuition", "Room and board", "Travel", "Field experience"],
    deadline: "2027-05-31",
    about: "For people with a track record of community service and peace-building work who want to deepen their skills.",
    essayPrompt: "Tell us about the work you have done for your community and what you want to change next.",
    essayTarget: 500,
    documents: ["Passport", "Transcripts", "CV", "Proof of 3 years' relevant experience"],
    referencesNeeded: 2,
    url: "https://www.rotary.org/en/our-programs/peace-fellowships",
  },
  {
    id: "aga-khan",
    name: "Aga Khan Foundation International Scholarship",
    provider: "Aga Khan Foundation",
    country: "Multiple",
    levels: ["Master's", "PhD"],
    fields: ["Any"],
    nationalities: [...africa, "India"],
    minGpa: 3.4,
    amountLabel: "50% grant, 50% loan",
    amountValue: 20000,
    fullyFunded: false,
    coverage: ["Half of costs as a grant", "Half as an interest-free loan"],
    deadline: "2027-03-31",
    about: "Postgraduate study for outstanding students from select developing countries who have no other means of financing their studies.",
    essayPrompt: "Explain your financial need and how your studies will serve your community.",
    essayTarget: 450,
    documents: ["Transcripts", "Proof of financial need", "Admission letter"],
    referencesNeeded: 2,
    url: "https://the.akdn/en/how-we-work/our-agencies/aga-khan-foundation",
  },
  {
    id: "australia-awards",
    name: "Australia Awards Scholarships",
    provider: "Government of Australia",
    country: "Australia",
    levels: ["Master's"],
    fields: ["Any"],
    nationalities: [...africa, "India"],
    minGpa: 3.0,
    amountLabel: "Full funding",
    amountValue: 60000,
    fullyFunded: true,
    coverage: ["Tuition", "Return air travel", "Living allowance", "Health cover"],
    deadline: "2027-04-30",
    about: "Long-term development scholarships for leaders from partner countries, focused on skills that help home-country priorities.",
    essayPrompt: "How will your study contribute to development priorities in your country?",
    essayTarget: 500,
    documents: ["Passport", "Transcripts", "CV", "Employer support letter"],
    referencesNeeded: 2,
    url: "https://www.dfat.gov.au/people-to-people/australia-awards",
  },
]

// ---- Demo content so the app doesn't open on a blank page. All of it is deletable. ----
export const seedPeople: Person[] = [
  {
    id: "p-claudine",
    name: "Dr. Claudine Mukamana",
    relationship: "Lecturer",
    email: "",
    canSpeakTo: "supervised my final-year project on clinic scheduling software",
  },
  {
    id: "p-eric",
    name: "Eric Habimana",
    relationship: "Former manager",
    email: "",
    canSpeakTo: "worked with me for two years at a health NGO",
  },
]

export const seedEssays: Essay[] = [
  {
    id: "e-story",
    title: "Why I build for clinics",
    prompt: "The story only you can tell. This is the one to adapt for other applications.",
    body:
      "When I was fourteen I sat with my aunt for six hours in a health centre waiting room because the appointment book had been lost. Nobody was careless. There was simply no better way.\n\nYears later, I wrote my first scheduling tool for a clinic in my district. It cut waiting from hours to minutes for around 300 patients a month. I still remember the nurse who told me she finally ate lunch.\n\nI want to keep building this kind of software, and I want to learn how to do it responsibly at scale.",
    createdAt: "2026-09-20T09:00:00.000Z",
    updatedAt: "2026-09-27T18:30:00.000Z",
    versions: [],
    notes: [
      {
        id: "n1",
        author: "Dr. Mukamana",
        text: "The waiting room is a strong opening. Say more about what you learned from the nurse's reaction.",
        createdAt: "2026-09-27T18:30:00.000Z",
      },
    ],
  },
]
